# Generated by Django 2.1.9 on 2019-07-19 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 6, 8, 5, 346742, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
