# Generated by Django 2.1.9 on 2019-07-19 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190719_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 6, 9, 3, 143802, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
