version: "2"

networks:
  personalsite_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static_volume:/app/personal_site_static  # <-- bind the static volume
      - media_volume:/app/personal_site_media  # <-- bind the media volume
    env_file:
      - ./.prod
    networks:
      - personalsite_network
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_volume:/app/personal_site_static  # <-- bind the static volume
      - media_volume:/app/personal_site_media  # <-- bind the media volume
    depends_on:
      - app
    networks:
      personalsite_network:
        ipv4_address: 10.5.0.6

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
