version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static_volume:/app/static  # <-- bind the static volume
      - media_volume:/app/media  # <-- bind the media volume
    env_file:
      - ./.prod
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    volumes:
      - static_volume:/app/static  # <-- bind the static volume
      - media_volume:/app/media  # <-- bind the media volume

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
