version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./.prod
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'