version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "gunicorn personalSite.wsgi:application --workers=2 --bind 0.0.0.0:8000"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'