# Generated by Django 3.0.2 on 2021-08-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200204_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
